### ISSUE TITLE
Allow ClusterHandlers to trigger retries in the cluster watcher

### ISSUE THREAD

**Issue by joekelley** [solo-io/skv2#53]
There are situations when ClusterHandlers may wish to trigger retries on the cluster watcher's secret reconciler. We should consider the side effects this might have on the cluster watcher itself, as well as on other ClusterHandlers, because each retry would cause all ClusterRemovedHandlers and ClusterHandlers to be called again.

To trigger an error, we would update the signature of ClusterAdded to return an error, and return that error form the ReconcileSecret function here: https://github.com/solo-io/skv2/blob/b975e59b10f1ba1b84f696ba2765384eb68c9f8e/pkg/multicluster/watch/watcher.go#L66

**Comment by jenshu** [comment]
this has been implemented by passing in [retry options](https://github.com/solo-io/skv2/blob/a96e0ccc0f6c6ba5898c4378b0210344a2cd8a46/pkg/multicluster/watch/watcher.go#L78) to the cluster watcher, which are then used within startManager [here](https://github.com/solo-io/skv2/blob/a96e0ccc0f6c6ba5898c4378b0210344a2cd8a46/pkg/multicluster/watch/watcher.go#L137)
